//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.1.4322.2032.
// 
using System.Diagnostics;
using System.Xml.Serialization;
using System;
using System.Web.Services.Protocols;
using System.ComponentModel;
using System.Web.Services;


/// <remarks/>
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="TranslationServiceSoap", Namespace="http://zeta-software.de/TranslationWebService")]
public class TranslationService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    /// <remarks/>
    public TranslationService() {
        this.Url = "http://www.zeta-software.de/Translator/TranslationService.asmx";
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://zeta-software.de/TranslationWebService/GetAllTranslationModes", RequestNamespace="http://zeta-software.de/TranslationWebService", ResponseNamespace="http://zeta-software.de/TranslationWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public TranslationMode[] GetAllTranslationModes() {
        object[] results = this.Invoke("GetAllTranslationModes", new object[0]);
        return ((TranslationMode[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetAllTranslationModes(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetAllTranslationModes", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public TranslationMode[] EndGetAllTranslationModes(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((TranslationMode[])(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://zeta-software.de/TranslationWebService/GetTranslationModeByObjectID", RequestNamespace="http://zeta-software.de/TranslationWebService", ResponseNamespace="http://zeta-software.de/TranslationWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public TranslationMode GetTranslationModeByObjectID(string objectID) {
        object[] results = this.Invoke("GetTranslationModeByObjectID", new object[] {
                    objectID});
        return ((TranslationMode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetTranslationModeByObjectID(string objectID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetTranslationModeByObjectID", new object[] {
                    objectID}, callback, asyncState);
    }
    
    /// <remarks/>
    public TranslationMode EndGetTranslationModeByObjectID(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((TranslationMode)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://zeta-software.de/TranslationWebService/Translate", RequestNamespace="http://zeta-software.de/TranslationWebService", ResponseNamespace="http://zeta-software.de/TranslationWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string Translate(TranslationMode translationMode, string textToTranslate) {
        object[] results = this.Invoke("Translate", new object[] {
                    translationMode,
                    textToTranslate});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginTranslate(TranslationMode translationMode, string textToTranslate, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Translate", new object[] {
                    translationMode,
                    textToTranslate}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndTranslate(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://zeta-software.de/TranslationWebService")]
public class TranslationMode {
    
    /// <remarks/>
    public string ObjectID;
    
    /// <remarks/>
    public string VisualNameEN;
    
    /// <remarks/>
    public string VisualNameDE;
}
